'use client'; // Menandakan ini adalah Client Component
import { useEffect } from 'react';
import { jsPDF } from 'jspdf';

interface LaporanData {
  id: string;
  total: number;
  tanggal: string;
}

interface ExportPDFButtonProps {
  laporanData: LaporanData[];
}

const ExportPDFButton: React.FC<ExportPDFButtonProps> = ({ laporanData }) => {
  const generatePDF = async () => {
    const doc = new jsPDF();

    // Ambil logo dari path file
    const logoUrl = '/logo.png'; // Path ke logo Anda di public folder

    // Fetch logo untuk mendapatkan data dalam format Blob
    const response = await fetch(logoUrl);
    const blob = await response.blob();

    // Convert Blob ke Base64
    const reader = new FileReader();
    reader.onloadend = () => {
      const logoBase64 = reader.result as string;

      // Tambahkan logo ke PDF
      doc.addImage(logoBase64, 'PNG', 10, 10, 30, 30);

      // Tambahkan judul
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(20);
      doc.text('Laporan Transaksi', 50, 20); // Judul diatur agar sejajar dengan logo

      // Tambahkan garis pemisah
      doc.setDrawColor(0); // Warna hitam
      doc.setLineWidth(0.5);
      doc.line(10, 45, 200, 45);

      // Menambahkan data laporan ke PDF
      doc.setFont('Helvetica', 'normal');
      doc.setFontSize(14);
      let yPosition = 60; // Posisi awal teks di Y
      const lineSpacing = 10; // Jarak antar baris

      laporanData.forEach((laporan) => {
        doc.text(`ID Transaksi: ${laporan.id}`, 10, yPosition);
        yPosition += lineSpacing;
        doc.text(`Total Transaksi: Rp ${laporan.total.toLocaleString('id-ID')}`, 10, yPosition);
        yPosition += lineSpacing;
        doc.text(`Tanggal Transaksi: ${laporan.tanggal}`, 10, yPosition);
        yPosition += lineSpacing * 2; // Jarak antar transaksi
      });

      // Tambahkan ucapan terima kasih
      yPosition += lineSpacing * 2; // Beri jarak lebih besar
      doc.setFontSize(12);
      doc.setTextColor(150);
      doc.text('Terima kasih atas transaksi Anda!', 10, yPosition);

      // Tambahkan footer
      yPosition += lineSpacing * 3; // Tambahkan lebih banyak ruang
      doc.setTextColor(100);
      doc.setFontSize(10);
      doc.text('Generated by Belikopi.', 10, 290, { align: 'left' });

      // Simpan file PDF
      doc.save('laporan_transaksi.pdf');
    };

    reader.readAsDataURL(blob);
  };

  return (
    <button
      onClick={generatePDF}
      className="bg-amber-800 text-white px-4 py-2 rounded-lg hover:bg-amber-700"
    >
      Export Laporan ke PDF
    </button>
  );
};

export default ExportPDFButton;
